In [2]:
import pandas as pd

Q1 Pandas version

What version of Pandas did you install?
You can get the version information using the `__version__` field:

In [3]:
pd.__version__

'3.0.6'

# Getting the data

In [4]:
df = pd.read_csv(r'C:\Users\sutov\Dev\ml_zoomcamp_my\car_fuel_efficiency_2026.csv')
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.columns.to_list()

['model_year',
 'origin',
 'fuel_type',
 'drivetrain',
 'num_doors',
 'engine_displacement',
 'num_cylinders',
 'horsepower',
 'vehicle_weight',
 'acceleration',
 'fuel_efficiency_mpg']

# Q2. Records count

In [6]:
df.shape[0]

10000

# Q3. Fuel types

In [7]:
df.loc[:, 'fuel_type'].nunique()

3

# Q4. Missing values

[](https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/main/cohorts/2026/homework/01-intro/homework.md#q4-missing-values)

How many columns in the dataset have missing values?

In [8]:
print(df.isnull().sum())
print("-------------------------------------------")
print(f"Number of rows with missing values: {(df.isnull().sum()>0).sum()}")

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64
-------------------------------------------
Number of rows with missing values: 2

# Q5. Max fuel efficiency

[](https://github.com/DataTalksClub/machine-learning-zoomcamp/blob/main/cohorts/2026/homework/01-intro/homework.md#q5-max-fuel-efficiency)

What's the maximum fuel efficiency of cars from Asia?

In [9]:
df.fuel_efficiency_mpg.max()

np.float64(41.2)

# Q6. Median value of horsepower

In [10]:
df.horsepower.median()

np.float64(254.0)

  Next, calculate the most frequent value of the same `horsepower` column.

In [11]:
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.

In [12]:
df2 = df.copy(deep=True)
df2.horsepower = df2.horsepower.fillna(df2.horsepower.mode()[0])

Has it changed?

In [13]:
df2.horsepower.median()

np.float64(252.0)

# Q7. Sum of weights

Select all the cars from Asia

In [14]:
df_asia = df[df['origin'] == 'Asia']
df_asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

Select only columns vehicle_weight and model_year

In [15]:
df_asia[['vehicle_weight', 'model_year']]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk a

In [16]:
import numpy as np

X = df_asia[['vehicle_weight', 'model_year']].head(7).to_numpy()
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
w = XTX_inv.dot(X.T).dot(y)
w.sum()

np.float64(0.36919696904925486)

df.horsepower.nvalues